export const orderingOptions = [
  { label: "Added", value: "added" },
  { label: "Name", value: "name" },
  { label: "Released", value: "released" },
  { label: "Rating", value: "rating" },
  { label: "Metacritic", value: "metacritic" },
];

export const genreOptions = [
  { label: "None", value: "" },
  { label: "Action", value: "action" },
  { label: "Indie", value: "indie" },
  { label: "Adventure", value: "adventure" },
  { label: "RPG", value: "role-playing-games-rpg" },
  { label: "Strategy", value: "strategy" },
  { label: "Shooter", value: "shooter" },
  { label: "Casual", value: "casual" },
  { label: "Simulation", value: "simulation" },
  { label: "Puzzle", value: "puzzle" },
  { label: "Arcade", value: "arcade" },
  { label: "Platformer", value: "platformer" },
  { label: "Racing", value: "racing" },
  { label: "Massively Multiplayer", value: "massively-multiplayer" },
  { label: "Sports", value: "sports" },
  { label: "Fighting", value: "fighting" },
  { label: "Family", value: "family" },
  { label: "Board Games", value: "board-games" },
  { label: "Educational", value: "educational" },
  { label: "Card", value: "card" },
];
